GET http://127.0.0.1:3000/api/auth/verify-token
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0ZDgxYTU2NjVlZDU2NWI5NDc1MTlkZCIsInVzZXJuYW1lIjoiYWRtaW4iLCJpYXQiOjE2OTE4ODY3OTIsImV4cCI6MTY5MTg5MDM5Mn0.b07ubNnIVTIie8lO2YVj-6Ql0poUR1m0FUW1l_xx-F4
