# fly.toml app configuration file generated for admin-backend-society on 2023-08-12T20:16:43Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "admin-backend-society"
primary_region = "mad"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
